import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
  weeklyContentSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      items: ['weekly-content/introduction'],
    },
    {
      type: 'category',
      label: 'Week 0: Setup',
      items: ['weekly-content/week-00'],
    },
    {
      type: 'category',
      label: 'Weeks 1-5: Foundations',
      items: [
        'weekly-content/week-01',
        'weekly-content/week-02',
        'weekly-content/week-03',
        'weekly-content/week-04',
        'weekly-content/week-05',
      ],
    },
    {
      type: 'category',
      label: 'Weeks 6-10: Intermediate',
      items: [
        'weekly-content/week-06',
        'weekly-content/week-07',
        'weekly-content/week-08',
        'weekly-content/week-09',
        'weekly-content/week-10',
      ],
    },
    {
      type: 'category',
      label: 'Weeks 11-15: Advanced',
      items: [
        'weekly-content/week-11',
        'weekly-content/week-12',
        'weekly-content/week-13',
        'weekly-content/week-14',
        'weekly-content/week-15',
      ],
    },
    {
      type: 'category',
      label: 'Weeks 16-20: Applications',
      items: [
        'weekly-content/week-16',
        'weekly-content/week-17',
        'weekly-content/week-18',
        'weekly-content/week-19',
        'weekly-content/week-20',
      ],
    },
  ],

  // Projects sidebar
  projectsSidebar: [
    {
      type: 'category',
      label: 'Projects',
      items: [
       'projects/project-01-matrix-operations',
      ],
    },
  ],

  // Notes sidebar
  notesSidebar: [
    {
      type: 'category',
      label: 'Course Notes',
      items: [
       'notes/numpy-overview',
      ],
    },
    {
      type: 'category',
      label: 'Concept Deep Dives',
      items: [
        'notes/numpy-dive',
      ],
    },
    {
      type: 'category',
      label: 'Dev Notes',
      items: [
        'notes/dev-notes/docusaurus-architecture',
        'notes/dev-notes/build-plugin-system-tutorial',
        'notes/dev-notes/confluence-api-integration',
        'notes/dev-notes/github-actions-guide',
      ],
    },
    {
      type: 'category',
      label: 'Docusaurus Notes',
      items: [
        {
          type: 'category',
          label: 'Tutorial Basics',
          items: [
            'notes/docusaurus-notes/tutorial-basics/create-a-page',
            'notes/docusaurus-notes/tutorial-basics/create-a-document',
            'notes/docusaurus-notes/tutorial-basics/create-a-blog-post',
            'notes/docusaurus-notes/tutorial-basics/markdown-features',
            'notes/docusaurus-notes/tutorial-basics/deploy-your-site',
            'notes/docusaurus-notes/tutorial-basics/congratulations',
          ],
        },
        {
          type: 'category',
          label: 'Tutorial Extras',
          items: [
            'notes/docusaurus-notes/tutorial-extras/manage-docs-versions',
            'notes/docusaurus-notes/tutorial-extras/translate-your-site',
          ],
        },
      ],
    },
  ],
};

export default sidebars;
